require('dotenv').config();
const { supabase } = require('../src/db/supabase');

const PRODUCTS = [
  // ── Eletroportáteis, Ferramentas e Utilidades ─────────────────────────────
  { name: 'Fritadeira Sem Óleo Oster OFRT400 4L',      url: 'https://www.magazineluiza.com.br/fritadeira-sem-oleo-preta-ofrt400-220v-oster/p/afhagej68k/ep/efso/',                                                                                                                                                                                                                                                                              store: 'magazineluiza', category: 'eletrodomesticos', active: true },
  { name: 'Fritadeira Forno e Fryer 25L Oster',        url: 'https://www.magazineluiza.com.br/fritadeira-eletrica-oster-forno-fryer-25-litros-inox-220v-ofor250/p/fb3c4c6441/ep/efso/?seller_id=continentalcenter',                                                                                                                                                                                                                              store: 'magazineluiza', category: 'eletrodomesticos', active: true },
  { name: 'Robô Aspirador WAP Robot W300',              url: 'https://loja.wap.ind.br/robo-aspirador-de-po-wap-robot-w300/p',                                                                                                                                                                                                                                                                                                                     store: 'wap',           category: 'casa',             active: true },
  { name: 'Parafusadeira Bosch Go 3.6V',               url: 'https://www.magazineluiza.com.br/parafusadeira-a-bateria-36v-06019h21e0-bosch-go/p/ed7cjb2c86/fs/pafu/',                                                                                                                                                                                                                                                                           store: 'magazineluiza', category: 'ferramentas',      active: true },
  { name: 'Sabão Líquido Omo Lavagem Perfeita 3L',      url: 'https://www.mercadolivre.com.br/sabo-liquido-omo-lavagem-perfeita-3l/p/MLB2050354955',                                                                                                                                                                                                                                                                                              store: 'mercadolivre',  category: 'casa',             active: true },

  // ── Games, Cadeiras e Periféricos ─────────────────────────────────────────
  { name: 'Console PlayStation 5 Edição Digital 825GB', url: 'https://www.kabum.com.br/produto/989702/console-sony-playstation-5-ssd-825gb-controle-sem-fio-dualsense-2-jogos-digitais-edicao-digital',                                                                                                                                                                                                                                          store: 'kabum',         category: 'games',            active: true },
  { name: 'Headset Razer BlackShark V2 X',              url: 'https://www.kabum.com.br/produto/183080/headset-gamer-razer-blackshark-v2-x-drivers-50mm-surround-7-1-3-5-mm-verde-rz04-03240600-r3u1',                                                                                                                                                                                                                                            store: 'kabum',         category: 'perifericos',      active: true },
  { name: 'Mouse Logitech G Pro X Superlight 2',        url: 'https://www.mercadolivre.com.br/mouse-gamer-sem-fio-logitech-g-pro-x-superlight-2-branco/p/MLB28294852',                                                                                                                                                                                                                                                                           store: 'mercadolivre',  category: 'perifericos',      active: true },
  { name: 'Cadeira Gamer Husky Gaming Snow',            url: 'https://www.kabum.com.br/produto/92752/cadeira-gamer-husky-gaming-snow-preto-e-branco-cilindro-de-gas-classe-4-base-em-metal-roda-em-nylon-hsn-bw',                                                                                                                                                                                                                                 store: 'kabum',         category: 'games',            active: true },
  { name: 'Monitor Gamer LG UltraGear 24" 180Hz',      url: 'https://www.kabum.com.br/produto/614879/monitor-gamer-lg-ultragear-24-fhd-180hz-1ms-ips-dp-e-hdmi-hdr10-freesync-g-sync-24gs60f-b',                                                                                                                                                                                                                                                store: 'kabum',         category: 'perifericos',      active: true },

  // ── Smartphones, Tablets e Componentes ───────────────────────────────────
  { name: 'Apple iPhone 15 128GB Preto',               url: 'https://www.mercadolivre.com.br/apple-iphone-15-128-gb-preto-distribuidor-autorizado/p/MLB1027172677',                                                                                                                                                                                                                                                                              store: 'mercadolivre',  category: 'smartphones',      active: true },
  { name: 'Samsung Galaxy S23 256GB 5G',               url: 'https://www.mercadolivre.com.br/samsung-galaxy-s23-256-gb-5g-preto-8-gb-ram/p/MLB21436188',                                                                                                                                                                                                                                                                                         store: 'mercadolivre',  category: 'smartphones',      active: true },
  { name: 'Samsung Galaxy Tab S9 FE 5G 128GB',         url: 'https://www.mercadolivre.com.br/tablet-samsung-galaxy-tab-s9-fe-5g-128gb-6gb-ram-tela-imersiva-de-109-90hz-camera-traseira-de-8mp-cmera-frontal-de-12mp-ultra-wide-wifi-6-ip68-android-14-verde-claro/p/MLB28529805',                                                                                                                                                               store: 'mercadolivre',  category: 'eletronicos',      active: true },
  { name: 'Processador AMD Ryzen 7 5700X',             url: 'https://www.mercadolivre.com.br/processador-amd-ryzen-7-5700x-oem-46ghz-8-nucleos-e-16-thed/p/MLB62338492',                                                                                                                                                                                                                                                                         store: 'mercadolivre',  category: 'hardware',         active: true },
  { name: 'Placa de Vídeo RTX 4060 Ti 16GB GDDR6',    url: 'https://www.mercadolivre.com.br/placa-de-video-rtx-4060-ti-16gb-gddr6-128bits-ventus-3x-oc/p/MLB29715221',                                                                                                                                                                                                                                                                           store: 'mercadolivre',  category: 'hardware',         active: true },
  { name: 'Smartphone Realme Note 50 128GB',           url: 'https://www.mercadolivre.com.br/celular-realme-note-50-dual-sim-128-gb-preto-4-gb-ram-novo-com-caixa-aberta/p/MLB2015828651',                                                                                                                                                                                                                                                        store: 'mercadolivre',  category: 'smartphones',      active: true },
  { name: 'Samsung Galaxy A30s 64GB',                  url: 'https://www.mercadolivre.com.br/samsung-galaxy-a30s-dual-sim-64-gb-prism-crush-white-4-gb-ram/p/MLB15303143',                                                                                                                                                                                                                                                                        store: 'mercadolivre',  category: 'smartphones',      active: true },

  // ── Casa Inteligente, Áudio e Leitura Digital ─────────────────────────────
  { name: 'Echo Dot 5ª Geração (KaBuM)',               url: 'https://www.kabum.com.br/produto/460472/echo-dot-5-geracao-amazon-com-alexa-smart-speaker-branco-b09b8xvsdp',                                                                                                                                                                                                                                                                       store: 'kabum',         category: 'eletronicos',      active: true },
  { name: 'Fire TV Stick Lite 2ª Geração (KaBuM)',     url: 'https://www.kabum.com.br/produto/349378/amazon-fire-tv-stick-lite-2-geracao-full-hd-hdmi-bluetooth-com-controle-remoto-por-voz-com-alexa-b091g767yb',                                                                                                                                                                                                                                store: 'kabum',         category: 'eletronicos',      active: true },
  { name: 'Kindle Paperwhite 11ª Geração 16GB',        url: 'https://www.pontofrio.com.br/kindle-paperwhite-amazon-11-geracao-com-16gb-tela-de-68-e-iluminacao-embutida-preto/p/55055972',                                                                                                                                                                                                                                                        store: 'pontofrio',     category: 'eletronicos',      active: true },
  { name: 'Fone JBL Tune 520BT Azul',                  url: 'https://www.mercadolivre.com.br/fone-de-ouvido-headphone-bluetooth-jbl-tune-520bt-cor-azul/p/MLB56414483',                                                                                                                                                                                                                                                                          store: 'mercadolivre',  category: 'audio',            active: true },
  { name: 'Samsung Galaxy Buds FE 2025',               url: 'https://www.mercadolivre.com.br/bluetooth-earbuds-samsung-galaxy-buds-3-fe-2025-gray/p/MLB2077168654',                                                                                                                                                                                                                                                                              store: 'mercadolivre',  category: 'audio',            active: true },

  // ── Moda, Acessórios e Perfumaria ─────────────────────────────────────────
  { name: 'Tênis Nike Revolution 6 Masculino',         url: 'https://www.dafiti.com.br/Tenis-Nike-Revolution-6-Next-Nature-Masculino-12126719.html',                                                                                                                                                                                                                                                                                              store: 'dafiti',        category: 'calcados',         active: true },
  { name: 'Tênis Vans Old Skool Preto',                url: 'https://www.dafiti.com.br/Tenis-Vans-Old-Skool-Preto-14772934.html',                                                                                                                                                                                                                                                                                                                 store: 'dafiti',        category: 'calcados',         active: true },
  { name: 'Tênis Puma Smash V2 BDP Preto',             url: 'https://www.dafiti.com.br/Tenis-Puma-Smash-V2-Bdp-Preto-3740164.html',                                                                                                                                                                                                                                                                                                               store: 'dafiti',        category: 'calcados',         active: true },
  { name: 'Jaqueta Calvin Klein Puffer Waterproof',    url: 'https://www.dafiti.com.br/Jaqueta-Calvin-Klein-Masculina-Puffer-Waterproof-Caqui-15166833.html',                                                                                                                                                                                                                                                                                     store: 'dafiti',        category: 'vestuario',        active: true },
  { name: 'Blusa Moletom GAP Logo',                    url: 'https://www.dafiti.com.br/Blusa-de-Moletom-Aberta-GAP-Logo-Marrom-11580219.html',                                                                                                                                                                                                                                                                                                    store: 'dafiti',        category: 'vestuario',        active: true },
  { name: 'Mochila Nike Heritage Unissex',             url: 'https://www.dafiti.com.br/Mochila-Nike-Heritage-Unissex-15060692.html',                                                                                                                                                                                                                                                                                                               store: 'dafiti',        category: 'acessorios',       active: true },
  { name: 'Relógio Casio Digital F-91WM-3ADF-SC',     url: 'https://www.dafiti.com.br/Relogio-Casio-Digital-F-91WM-3ADF-SC-Verde-13177176.html',                                                                                                                                                                                                                                                                                                  store: 'dafiti',        category: 'acessorios',       active: true },
  { name: 'Perfume CK One Eau de Toilette 100ml',      url: 'https://www.dafiti.com.br/Perfume-100ml-Ck-One-Eau-de-Toilette-Calvin-Klein-Unissex-13358208.html',                                                                                                                                                                                                                                                                                   store: 'dafiti',        category: 'perfumaria',       active: true },
  { name: 'Óculos de Sol Ray-Ban Essentials Chumbo',   url: 'https://www.dafiti.com.br/Oculos-de-Sol-Ray-Ban-Essentials-Chumbo-0RB3445-004-64-15082493.html',                                                                                                                                                                                                                                                                                     store: 'dafiti',        category: 'acessorios',       active: true },

  // ── Acessórios Galaxy Buds ────────────────────────────────────────────────
  { name: 'Capa Prova de Choque Galaxy Buds FE',       url: 'https://produto.mercadolivre.com.br/MLB-6691770124-capa-prova-de-choque-t-para-galaxy-buds-fe-capa-para-fo-_JM',                                                                                                                                                                                                                                                                    store: 'mercadolivre',  category: 'acessorios',       active: true },
  { name: 'Estojo de Carregamento Galaxy Buds FE',     url: 'https://produto.mercadolivre.com.br/MLB-5907332540-estojo-de-carregamento-para-galaxy-buds-fe-_JM',                                                                                                                                                                                                                                                                                  store: 'mercadolivre',  category: 'acessorios',       active: true },
];

async function seed() {
  console.log(`Inserindo ${PRODUCTS.length} produtos...\n`);

  const { data, error } = await supabase
    .from('products')
    .upsert(PRODUCTS, { onConflict: 'url', ignoreDuplicates: false })
    .select('name, store, active');

  if (error) {
    console.error('Erro ao inserir produtos:', error.message);
    process.exit(1);
  }

  data.forEach((p) => {
    const status = p.active ? '✓' : '○';
    console.log(`${status} [${p.store.padEnd(14)}] ${p.name}`);
  });

  console.log(`\n${data.length} produto(s) inseridos/atualizados com sucesso.`);
}

seed();
