require('dotenv').config();
const { supabase } = require('../src/db/supabase');

const PRODUCTS = [
  // ── Mercado Livre ─────────────────────────────────────────────────────────────
  { name: 'Apple iPhone 16 Pro 128GB Titânio Branco',                url: 'https://www.mercadolivre.com.br/apple-iphone-16-pro-128-gb-titnio-branco/p/MLB40287849',                                                                                                                                                                                                                                store: 'mercadolivre', category: 'eletronicos', active: true },
  { name: 'Samsung Galaxy S25 5G 256GB Azul Marinho',                url: 'https://www.mercadolivre.com.br/samsung-galaxy-s25-5g-256gb-12gb-cmera-tripla-azul-marinho/p/MLB45502223',                                                                                                                                                                                                              store: 'mercadolivre', category: 'eletronicos', active: true },
  { name: 'Samsung Galaxy S26 Ultra 5G 256GB Preto',                 url: 'https://www.mercadolivre.com.br/celular-samsung-galaxy-s26-ultra-5g-256gb-12gb-ram-cmera-quadrupla-tela-grande-de-69-preto/p/MLB65503984',                                                                                                                                                                              store: 'mercadolivre', category: 'eletronicos', active: true },
  { name: 'Apple Watch Series 11 46mm GPS Alumínio',                 url: 'https://www.mercadolivre.com.br/apple-watch-series-11-gps-caixa-cinza-espacial-de-aluminio-46-mm-pulseira-esportiva-preta-mg-distribuidor-autorizado/p/MLB1054112179',                                                                                                                                                  store: 'mercadolivre', category: 'eletronicos', active: true },
  { name: 'Tablet Samsung Galaxy Tab S9 FE 5G 128GB',                url: 'https://www.mercadolivre.com.br/tablet-samsung-galaxy-tab-s9-fe-5g-128gb-6gb-ram-tela-imersiva-de-109-90hz-camera-traseira-de-8mp-cmera-frontal-de-12mp-ultra-wide-wifi-6-ip68-android-14-verde-claro/p/MLB28529805',                                                                                                    store: 'mercadolivre', category: 'eletronicos', active: true },
  { name: 'Câmera de Ação Insta360 X4 8K',                           url: 'https://www.mercadolivre.com.br/insta360-x4-8k-360-action-cmera-360-60fps-para-streaming-profissional-inteligncia-artificial-com-sensor-de-rastreamento-e-controle-de-gestos-prova-dagua-efeito-basto-de-selfie-invisivel/p/MLB36223181',                                                                               store: 'mercadolivre', category: 'eletronicos', active: true },
  { name: 'Dyson Airwrap Multiestilizador Complete Long',            url: 'https://www.mercadolivre.com.br/dyson-airwrap-multiestilizador-de-cabelo-completo/p/MLB50522412',                                                                                                                                                                                                                       store: 'mercadolivre', category: 'beleza',      active: true },
  { name: 'Console Portátil Steam Deck OLED 512GB',                  url: 'https://www.mercadolivre.com.br/steam-deck-oled-512gb/p/MLB27635201',                                                                                                                                                                                                                                                   store: 'mercadolivre', category: 'eletronicos', active: true },
  { name: 'Fone de Ouvido Bose QuietComfort Ultra Preto',            url: 'https://www.mercadolivre.com.br/fone-de-ouvido-over-ear-sem-fio-bose-quietcomfort-ultra-preto/p/MLB28467117',                                                                                                                                                                                                           store: 'mercadolivre', category: 'eletronicos', active: true },
  { name: 'Body Mist Sol de Janeiro Cheirosa 62 240ml',              url: 'https://www.mercadolivre.com.br/sol-de-janeiro-brazilian-crush-cheirosa-62-body-mist-fem-240ml/p/MLB24244613',                                                                                                                                                                                                          store: 'mercadolivre', category: 'beleza',      active: true },
  { name: 'Perfume Sol de Janeiro Cheirosa 62 Eau de Parfum 50ml',   url: 'https://www.mercadolivre.com.br/perfume-sol-de-janeiro-cheirosa-62-eau-de-parfum-50ml-amadeirado/p/MLB21401853',                                                                                                                                                                                                        store: 'mercadolivre', category: 'beleza',      active: true },
  { name: 'Placa de Vídeo RTX 4060 Ti 16GB GDDR6 Ventus 3X OC',      url: 'https://www.mercadolivre.com.br/placa-de-video-rtx-4060-ti-16gb-gddr6-128bits-ventus-3x-oc/p/MLB29715221',                                                                                                                                                                                                              store: 'mercadolivre', category: 'hardware',    active: true },
  { name: 'Processador AMD Ryzen 7 5700X 8-Core',                    url: 'https://www.mercadolivre.com.br/processador-amd-ryzen-7-5700x-oem-46ghz-8-nucleos-e-16-thed/p/MLB62338492',                                                                                                                                                                                                             store: 'mercadolivre', category: 'hardware',    active: true },

  // ── KaBuM ─────────────────────────────────────────────────────────────────────
  { name: 'Console Sony PlayStation 5 Digital Edition 825GB',        url: 'https://www.kabum.com.br/produto/989702/console-sony-playstation-5-ssd-825gb-controle-sem-fio-dualsense-2-jogos-digitais-edicao-digital',                                                                                                                                                                              store: 'kabum',        category: 'eletronicos', active: true },
  { name: 'Monitor Gamer LG UltraGear 24" FHD 180Hz 1ms',           url: 'https://www.kabum.com.br/produto/614879/monitor-gamer-lg-ultragear-24-fhd-180hz-1ms-ips-dp-e-hdmi-hdr10-freesync-g-sync-24gs60f-b',                                                                                                                                                                                     store: 'kabum',        category: 'hardware',    active: true },
  { name: 'Headset Gamer Razer BlackShark V2 X 7.1',                 url: 'https://www.kabum.com.br/produto/183080/headset-gamer-razer-blackshark-v2-x-drivers-50mm-surround-7-1-3-5-mm-verde-rz04-03240600-r3u1',                                                                                                                                                                                 store: 'kabum',        category: 'hardware',    active: true },
  { name: 'Echo Dot 5ª Geração Amazon Alexa Branco',                 url: 'https://www.kabum.com.br/produto/460472/echo-dot-5-geracao-amazon-com-alexa-smart-speaker-branco-b09b8xvsdp',                                                                                                                                                                                                           store: 'kabum',        category: 'eletronicos', active: true },
  { name: 'Cadeira Gamer Husky Gaming Snow',                         url: 'https://www.kabum.com.br/produto/92752/cadeira-gamer-husky-gaming-snow-preto-e-branco-cilindro-de-gas-classe-4-base-em-metal-roda-em-nylon-hsn-bw',                                                                                                                                                                     store: 'kabum',        category: 'casa',        active: true },

  // ── Dafiti ────────────────────────────────────────────────────────────────────
  { name: 'Tênis adidas Originals SL 72 RS Preto',                   url: 'https://www.dafiti.com.br/Tenis-adidas-Originals-SL-72-RS-Preto-13985423.html',                                                                                                                                                                                                                                          store: 'dafiti',       category: 'calcados',    active: true },
  { name: 'Tênis New Balance 1906R Preto',                           url: 'https://www.dafiti.com.br/Tenis-New-Balance-1906R-Preto-14737811.html',                                                                                                                                                                                                                                                  store: 'dafiti',       category: 'calcados',    active: true },
  { name: 'Tênis Puma Smash V2 BDP Preto',                           url: 'https://www.dafiti.com.br/Tenis-Puma-Smash-V2-Bdp-Preto-3740164.html',                                                                                                                                                                                                                                                   store: 'dafiti',       category: 'calcados',    active: true },
  { name: 'Jaqueta Calvin Klein Masculina Puffer Waterproof Caqui',  url: 'https://www.dafiti.com.br/Jaqueta-Calvin-Klein-Masculina-Puffer-Waterproof-Caqui-15166833.html',                                                                                                                                                                                                                         store: 'dafiti',       category: 'vestuario',   active: true },
  { name: 'Blusa de Moletom Aberta GAP Logo Marrom',                 url: 'https://www.dafiti.com.br/Blusa-de-Moletom-Aberta-GAP-Logo-Marrom-11580219.html',                                                                                                                                                                                                                                        store: 'dafiti',       category: 'vestuario',   active: true },
  { name: 'Mochila Nike Heritage Unissex',                           url: 'https://www.dafiti.com.br/Mochila-Nike-Heritage-Unissex-12366021.html',                                                                                                                                                                                                                                                  store: 'dafiti',       category: 'acessorios',  active: true },

  // ── Netshoes ──────────────────────────────────────────────────────────────────
  { name: 'Tênis Olympikus Corre 4 Chumbo e Bege',                   url: 'https://www.netshoes.com.br/p/tenis-olympikus-corre-4-chumbo+bege-2I3-0603-933',                                                                                                                                                                                                                                          store: 'netshoes',     category: 'calcados',    active: true },
  { name: 'Chuteira Futsal Umbro Pro 5 Bump Unissex',                url: 'https://www.netshoes.com.br/p/chuteira-futsal-umbro-pro-5-bump-unissex-branco+preto-2IA-2818-028',                                                                                                                                                                                                                        store: 'netshoes',     category: 'calcados',    active: true },
  { name: 'Tênis Adidas Runfalcon 3 Masculino Branco/Preto',         url: 'https://www.netshoes.com.br/p/tenis-adidas-runfalcon-3-masculino-branco+preto-FBA-6528-028',                                                                                                                                                                                                                              store: 'netshoes',     category: 'calcados',    active: true },
  { name: 'Tênis Hoka Clifton 9 Masculino Laranja',                  url: 'https://www.netshoes.com.br/p/tenis-hoka-clifton-9-masculino-laranja-AXF-0631-042',                                                                                                                                                                                                                                       store: 'netshoes',     category: 'calcados',    active: true },
  { name: 'Camisa Nike Seleção Brasileira Feminina I 2024/25',       url: 'https://www.netshoes.com.br/p/camisa-nike-selecao-brasileira-feminina-i-202425-torcedora-pro-feminina-amarelo-JD8-7860-030',                                                                                                                                                                                              store: 'netshoes',     category: 'vestuario',   active: true },

  // ── WAP ───────────────────────────────────────────────────────────────────────
  { name: 'Robô Aspirador de Pó WAP Robot W300',                     url: 'https://loja.wap.ind.br/robo-aspirador-de-po-wap-robot-w300/p',                                                                                                                                                                                                                                                          store: 'wap',          category: 'casa',        active: true },

  // ── Amazon ────────────────────────────────────────────────────────────────────
  { name: 'Kindle Paperwhite 16GB 11ª Geração',                      url: 'https://www.amazon.com.br/dp/B0CFPL6CFY',                                                                                                                                                                                                                                                                                  store: 'amazon',       category: 'eletronicos', active: true },
];

async function main() {
  console.log(`Inserindo/atualizando ${PRODUCTS.length} produtos...`);

  const { data, error } = await supabase
    .from('products')
    .upsert(PRODUCTS, { onConflict: 'url' })
    .select('id, name');

  if (error) {
    console.error('Erro:', error.message);
    process.exit(1);
  }

  console.log(`\n${data.length} produto(s) inseridos/atualizados:`);
  data.forEach((p) => console.log(`  #${p.id} — ${p.name}`));
  process.exit(0);
}

main();
